# This is an action that builds the document and deploys the build document
# to its associated GitHub pages site.

name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare to build the document.
      shell: bash
      run: tools/build/prebuild
    - name: Build the document.
      shell: bash
      run: tools/build/build -d ${{runner.temp}}/output -z ${{github.ref}}
    - name: Deploy the built document to a GitHub Pages branch.
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      shell: bash
      run: |
        tools/build/deploy \
          -f \
          -t ${{runner.temp}}/deploy_tmp_2 \
          -i ${{runner.temp}}/output \
          -r mdadams/SG20 \
          -z ${{github.ref}}
    - name: Deploy the built document to a GitHub Pages branch.
      env:
        DEPLOY_KEY: ${{secrets.ALT_DEPLOY_KEY}}
      shell: bash
      run: |
        tools/build/deploy \
          -f \
          -t ${{runner.temp}}/deploy_tmp \
          -i ${{runner.temp}}/output \
          -r mdadams/sg20_guidelines_for_teaching_cpp \
          -z ${{github.ref}}
